---
- name: Installing the Nginx and configuring it
  hosts: webserver
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: started nginx
      service:
        name: nginx
        state: started
        enabled: true    